"""add avatar field to User

Revision ID: 997c72a07cf1
Revises: df78edc0b7a8
Create Date: 2018-07-23 10:12:12.526441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997c72a07cf1'
down_revision = 'df78edc0b7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
