"""del avatar field from User

Revision ID: b46788bef1af
Revises: 997c72a07cf1
Create Date: 2018-07-23 10:20:52.292586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b46788bef1af'
down_revision = '997c72a07cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('avatar', table_name='user')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('avatar', 'user', ['avatar'], unique=True)
    # ### end Alembic commands ###
